{pkgs, pkgs-stable, ...} : {
  home.packages = [
    pkgs.prismlauncher
    pkgs.haruna
    pkgs.mpv
    pkgs.piper
    pkgs.solaar
    pkgs.flameshot
    pkgs.vscode-fhs
    pkgs-stable.jetbrains.idea-community
    pkgs-stable.anki
    pkgs.thunderbird
    pkgs.krita
    pkgs.aseprite
    pkgs-stable.chatterino7
    pkgs.dconf-editor
    pkgs.mission-center
    pkgs.hardinfo2
    pkgs.rustdesk
    pkgs.mediawriter
    pkgs.dino
    pkgs.streamlink
    pkgs.resources
    pkgs.melonDS
    pkgs.gpick
    pkgs.p7zip
    pkgs.peazip
    pkgs.blockbench
    pkgs.pinta
    pkgs.obs-studio
    pkgs.kdePackages.ark
    pkgs.imhex
    pkgs.jetbrains.rider
  ];
}
