{
  imports = [
    ./bootloader.nix
    ./user.nix
    #./xfce.nix
    ./sound.nix
    ./bluetooth.nix
    #./xfconf.nix
    ./git.nix
    ./nvidia.nix
    ./cinnamon.nix
    ./steam.nix
    ./java.nix
    ./filesystem.nix
    #./pinta.nix
    ./appimage.nix
    ./wine.nix
    ./hyprland.nix
    ./discord.nix
  ];
}
